# Permalinks
permalink:           pretty

# Setup
title:               Чёрным по белому
tagline:             Daria Pydorenko
paginate:            10
baseurl:             "/old_blog"

# About/contact
author:
  name:              Daria Pydorenko
  email:             venka.daria@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/venkaDaria/old_blog

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
  - jemoji

# SSL error
gist:
  noscript: false

# Customization
pages_list:
  О блоге: '/old_blog/about'
  Архив записей: '/old_blog/archive'
  Лента: '/old_blog/atom.xml'

# for related post
related_posts_max : 6
